stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go/src/github.com/nicusirb
        ln -s `pwd` /go/src/github.com/nicusirb/pipeline-example-go
        cd /go/src/github.com/nicusirb/pipeline-example-go
        go build -o bin/hello-server
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/example-helloserver:test
      pushRemote: true
      registry: olbank.advahoo.ro:4443
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
